**Exploration** (**pandas**)

Data Exploration in Pandas is the process of examining, understanding,
and summarizing a dataset before performing analysis or modeling.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dsml_pandas/titanic (1).csv")

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

**Normalize**

In [6]:
# value(0-1) range ma rakdinxa

In [7]:
df.value_counts(["Sex", "Survived"])

Sex     Survived
male    0           468
female  1           233
male    1           109
female  0            81
Name: count, dtype: int64

In [8]:
df.value_counts(["Sex", "Survived"], normalize = True)

Sex     Survived
male    0           0.525253
female  1           0.261504
male    1           0.122334
female  0           0.090909
Name: proportion, dtype: float64

In [9]:
468/891

0.5252525252525253

**correlation** **and** **covariance**

2 ota or more variable ko relation (dependent kati xa herni ho)

study time vs result = high/low/medium

age vs shoes size

To see relationaship between them is called correlation and covariance

In [10]:
df.value_counts(["Sex", "Survived"], normalize = True, ascending = True)

Sex     Survived
female  0           0.090909
male    1           0.122334
female  1           0.261504
male    0           0.525253
Name: proportion, dtype: float64

In [11]:
survived_female = df[(df['Survived'] == 1) & (df['Sex'] == 'female')]
survived_female

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [14]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [15]:
df["Embarked"].nunique()

3

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [18]:
# Using groupby()
df.groupby(['Embarked', 'Survived']).mean(numeric_only = True)

                   PassengerId    Pclass        Age     SibSp     Parch  \
Embarked Survived
C        0          409.853333  2.200000  33.666667  0.253333  0.253333
         1          473.989247  1.634409  28.973671  0.494624  0.451613
Q        0          480.404255  2.936170  30.325000  0.510638  0.276596
         1          319.966667  2.866667  22.500000  0.300000  0.000000
S        0          449.868852  2.545667  30.203966  0.611241  0.348946
         1          448.857143  1.967742  28.113184  0.493088  0.539171

                        Fare
Embarked Survived
C        0         35.443335
         1         79.720926
Q        0         13.335904
         1         13.182227
S        0         20.743987
         1         39.547081

Difference between Correlation and Covariance

In [19]:
df[["Age", "Fare"]].cov()

             Age         Fare
Age   211.019125    73.849030
Fare   73.849030  2469.436846

In [20]:
df[["Age", "Fare"]].corr()

           Age      Fare
Age   1.000000  0.096067
Fare  0.096067  1.000000

**Sampling**

In [23]:
sampled = df.sample(n=100, random_state=42)

In [22]:
sampled[["Age", "Fare"]].corr()

           Age      Fare
Age   1.000000  0.148739
Fare  0.148739  1.000000

In [24]:
 df[(df['Survived'] == 1) & df["Sex"] ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Build a Survival Profile :

You are hired as a data analyst to identify
the "most likely survivor.

"
Task:

Analyze survival by:

Gender

Passenger Class

Age Group

Fare

Based on your findings, describe the
characteristics of a passenger with the
highest chance of survival.

In [25]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [26]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [27]:
bins = [0,12,18,35,60,100]
labels = ["child", "Teens", "Young", "Adult", "Old"]
df["Age_Group"] = pd.cut(df["Age"], bins = bins, labels = labels)
df["Age_Group"]

0      Young
1      Adult
2      Young
3      Young
4      Young
       ...
886    Young
887    Young
888      NaN
889    Young
890    Young
Name: Age_Group, Length: 891, dtype: category
Categories (5, object): ['child' < 'Teens' < 'Young' < 'Adult' < 'Old']

Embarkation Port Analysis:

The company wants to know which port contributed the most passengers.

Task:

Count passengers from each embarkation port (Embarked).

Calculate the survival rate for each port.

Identify the port with the highest survival rate

In [28]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [29]:
df.groupby("Embarked")["Survived"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [30]:
summary = df.groupby("Embarked")["Survived"].agg(["count", "mean"])
summary.columns = ["Passenger_Count", "Survival_Rate"]
summary

          Passenger_Count  Survival_Rate
Embarked
C                     168       0.553571
Q                      77       0.389610
S                     644       0.336957