Panda

1)series --1D

2)Data frame --2D

In [ ]:
import pandas as pd

In [ ]:
a = ['g', 'h','i', 'j']
res = pd.Series(a)
res

0    g
1    h
2    i
3    j
dtype: object

In [ ]:
a = ['1', '3', '4', '6']
res = pd.Series(a, index = ['a', 'b', 'c', 'd'], dtype='int8', name = 'list of number', copy=True)
res

a    1
b    3
c    4
d    6
Name: list of number, dtype: int8

In [ ]:
#Series holding the dictionary
dict = {
    'id':1,
    'Name': 'Paru',
    'State': 'Ktm',
    'Age': 21
}
res_dict = pd.Series(dict)
res_dict

id          1
Name     Paru
State     Ktm
Age        21
dtype: object

DataFrame

In [ ]:
# Simpe Data Frame
data = ['python', 'pandas', 'Numpy']
df = pd.DataFrame(data)
df

        0
0  python
1  pandas
2   Numpy

In [ ]:
data = ['python', 'pandas', 'Numpy']
df = pd.DataFrame(data, index = ['a', 'b', 'c'] ,columns = ['Tech'])
df

     Tech
a  python
b  pandas
c   Numpy

In [ ]:
# Dictionary
dict1_data = {
    'Name': ['Paru','Ram', 'Ravi'],
    'Marks': [80,86,90],
}
res_dict = pd.DataFrame(dict1_data, index =['1', '2', '3'], columns=None,copy = True )
res_dict

   Name  Marks
1  Paru     80
2   Ram     86
3  Ravi     90

In [ ]:
res_dict[['Name']]

   Name
1  Paru
2   Ram
3  Ravi

In [ ]:
res_dict[['Marks']]

   Marks
1     80
2     86
3     90

In [ ]:
new_df = pd.DataFrame({
    'Name': ['Paru', "Ram", "Hari"],
    "Age": [23,43,54]
})
new_df

   Name  Age
0  Paru   23
1   Ram   43
2  Hari   54

In [ ]:
new_df.loc[1]

Name    Ram
Age      43
Name: 1, dtype: object

In [ ]:
new_df.iloc[1]

Name    Ram
Age      43
Name: 1, dtype: object

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dsml_pandas/titanic.csv")

In [5]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
df.sex

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: object

In [7]:
df['sex']

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: object

In [8]:
df.head() # Agadi ko 5 ota aauxa

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
df.head(2) # head ko limit xai 5 ota ho

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [10]:
df.tail() # end ko 5 ota dinxa

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [12]:
df.shape # gives rows and column

(891, 15)

In [13]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [17]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [22]:
df.iloc[1:2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [23]:
df.loc[1:2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

Difference between iloc ans loc in Pandas

loc is label based and iloc is integer position based.

In [29]:
new_df = pd.DataFrame({
    'Name': ["Ram", "Shyam", "Hari"],
    "Age": [23, 43, 54]
}, index =['a', 'b', 'c'])
new_df

    Name  Age
a    Ram   23
b  Shyam   43
c   Hari   54

In [30]:
# Error occured due to not labelling it
new_df.loc[1]

KeyError: 1

After labelling it

In [32]:
new_df.loc['a']

Name    Ram
Age      23
Name: a, dtype: object

In [31]:
new_df.iloc[1]

Name    Shyam
Age        43
Name: b, dtype: object

In [36]:
survived = df[(df['survived']==1)]
survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [38]:
survived = df[(df['survived'] == 1) & (df['sex'] == 'female')]
survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [39]:
survived = df[(df['survived']== 1) & (df['sex'] =="male")]
survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [40]:
survived.count()

survived       109
pclass         109
sex            109
age             93
sibsp          109
parch          109
fare           109
embarked       109
class          109
who            109
adult_male     109
deck            45
embark_town    109
alive          109
alone          109
dtype: int64

In [42]:
fare = df[df[('fare')] > 100]
fare

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
332,0,1,male,38.00,0,1,153.4625,S,First,man,True,C,Southampton,no,False
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
438,0,1,male,64.00,1,4,263.0000,S,First,man,True,C,Southampton,no,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,NaN,Cherbourg,yes,True
544,0,1,male,50.00,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
659,0,1,male,58.00,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False

In [43]:
survived_fare = df[(df['survived']== 1) & (df['fare'] >100)]
survived_fare

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,NaN,Cherbourg,yes,True
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False

In [44]:
# Available xa vane True garo xaina vane False garo
df['deck'].isna()

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: deck, Length: 891, dtype: bool

In [45]:
df['embarked'].duplicated()

0      False
1      False
2       True
3       True
4       True
       ...
886     True
887     True
888     True
889     True
890     True
Name: embarked, Length: 891, dtype: bool

In [46]:
# It checks not null value
df[df['deck'].notna()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True